title: stripe-checkout.pages.settings.title

icon: cog

options:
  changeSlug: false
  changeStatus: false
  changeTemplate: false
  create: false
  delete: false
  duplicate: false
  move: false
  preview: false

columns:
  shippingHeadline:
    width: 1/4
    fields:
      shippingHeadline:
        type: headline
        label: stripe-checkout.fields.settings.shippingHeadline.label
  shippingSection:
    width: 3/4
    fields:
      shippingEnabled:
        label: stripe-checkout.fields.settings.shippingEnabled.label
        type: toggle
      shippingAllowedCountries:
        label: stripe-checkout.fields.settings.shippingAllowedCountries.label
        type: multiselect
        min: 1
        options:
          type: api
          url: "{{ site.stripeCountriesUrl(user.language) }}"
        when:
          shippingEnabled: true
      shippingOptions:
        label: stripe-checkout.fields.settings.shippingOptions.label
        type: structure
        columns:
          name: true
          amount:
            align: right
        fields:
          name:
            label: stripe-checkout.fields.settings.shippingOptions.name.label
            type: text
            required: true
          amount:
            label: stripe-checkout.fields.settings.shippingOptions.amount.label
            type: number
            required: true
            min: 0
            step: .01
            after: "{{ site.stripeCurrencySymbol }}"
          deliveryEstimateMin:
            label: stripe-checkout.fields.settings.shippingOptions.deliveryEstimateMin.label
            type: number
            width: 1/2
            min: 1
            step: 1
            help: stripe-checkout.fields.settings.shippingOptions.deliveryEstimateMin.help
          deliveryEstimateMinUnit:
            label: stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.label
            type: select
            width: 1/2
            required: true
            default: business_day
            options:
              hour: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.hour') }}"
              day: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.day') }}"
              business_day: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.businessDay') }}"
              week: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.week') }}"
              month: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.month') }}"
          deliveryEstimateMax:
            label: stripe-checkout.fields.settings.shippingOptions.deliveryEstimateMax.label
            type: number
            width: 1/2
            min: 1
            step: 1
            help: stripe-checkout.fields.settings.shippingOptions.deliveryEstimateMax.help
          deliveryEstimateMaxUnit:
            label: stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.label
            type: select
            width: 1/2
            required: true
            default: business_day
            options:
              hour: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.hour') }}"
              day: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.day') }}"
              business_day: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.businessDay') }}"
              week: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.week') }}"
              month: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.month') }}"
        when:
          shippingEnabled: true
