title: Checkout Settings

icon: cog

options:
  changeSlug: false
  changeStatus: false
  changeTemplate: false
  create: false
  delete: false
  duplicate: false
  move: false
  preview: false

fields:
  shippingEnabled:
    label: Shipping
    type: toggle
    translate: false
  shippingAllowedCountries:
    label: Allowed countries
    type: multiselect
    options:
      type: api
      url: "{{ site.url }}/api/{{ user.language }}/stripe/countries"
    translate: false
    min: 1
    when:
      shippingEnabled: true
  shippingOptions:
    label: Delivery options
    type: structure
    columns:
      name: true
      amount:
        align: right
    fields:
      name:
        label: Name
        type: text
        required: true
      amount:
        label: Amount
        type: number
        step: .01
        required: true
        min: 0
        translate: false
      deliveryEstimateMinimumValue:
        label: Minimum delivery estimate
        type: number
        width: 1/2
        step: 1
        min: 1
        translate: false
        help: Leave empty if there is no minimum delivery estimate
      deliveryEstimateMinimumUnit:
        label: false
        type: select
        width: 1/2
        required: true
        default: business_day
        options:
          hour: Hours
          day: Days
          business_day: Business days
          week: Weeks
          month: Months
        translate: false
      deliveryEstimateMaximumValue:
        label: Maximum delivery estimate
        type: number
        width: 1/2
        step: 1
        min: 1
        translate: false
        help: Leave empty if there is no maximum delivery estimate
      deliveryEstimateMaximumUnit:
        label: false
        type: select
        width: 1/2
        required: true
        default: business_day
        options:
          hour: Hours
          day: Days
          business_day: Business days
          week: Weeks
          month: Months
        translate: false
    when:
      shippingEnabled: true
