title: stripe-checkout.pages.settings.title

icon: cog

options:
  changeSlug: false
  changeStatus: false
  changeTemplate: false
  create: false
  delete: false
  duplicate: false
  move: false
  preview: false

fields:
  shippingEnabled:
    label: stripe-checkout.fields.settings.shippingEnabled.label
    type: toggle
    translate: false
  shippingAllowedCountries:
    label: stripe-checkout.fields.settings.shippingAllowedCountries.label
    type: multiselect
    min: 1
    options:
      type: api
      url: "{{ kirby.url }}/api/stripe/countries?locale={{ user.language }}"
    translate: false
    when:
      shippingEnabled: true
  shippingOptions:
    label: stripe-checkout.fields.settings.shippingOptions.label
    type: structure
    columns:
      name: true
      amount:
        align: right
    fields:
      name:
        label: stripe-checkout.fields.settings.shippingOptions.name.label
        type: text
        required: true
      amount:
        label: stripe-checkout.fields.settings.shippingOptions.amount.label
        type: number
        required: true
        min: 0
        step: .01
        before: "{{ site.stripeCurrencySymbol }}"
        translate: false
      deliveryEstimateMinimum:
        label: stripe-checkout.fields.settings.shippingOptions.deliveryEstimateMinimum.label
        type: number
        width: 1/2
        min: 1
        step: 1
        translate: false
        help: stripe-checkout.fields.settings.shippingOptions.deliveryEstimateMinimum.help
      deliveryEstimateMinimumUnit:
        label: false
        type: select
        width: 1/2
        required: true
        default: business_day
        options:
          hour: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.hour') }}"
          day: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.day') }}"
          business_day: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.businessDay') }}"
          week: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.week') }}"
          month: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.month') }}"
        translate: false
      deliveryEstimateMaximum:
        label: stripe-checkout.fields.settings.shippingOptions.deliveryEstimateMaximum.label
        type: number
        width: 1/2
        min: 1
        step: 1
        translate: false
        help: stripe-checkout.fields.settings.shippingOptions.deliveryEstimateMaximum.help
      deliveryEstimateMaximumUnit:
        label: false
        type: select
        width: 1/2
        required: true
        default: business_day
        options:
          hour: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.hour') }}"
          day: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.day') }}"
          business_day: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.businessDay') }}"
          week: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.week') }}"
          month: "{{ t('stripe-checkout.fields.settings.shippingOptions.deliveryEstimateUnit.options.month') }}"
        translate: false
    when:
      shippingEnabled: true
