title: Product

options:
  changeTemplate: false
  move: false
  delete: false

columns:
  left:
    width: 2/3
    fields:
      price: stripe.checkout.fields/price
      tax: stripe.checkout.fields/tax
  right:
    width: 1/3
    fields:
      cover: stripe.checkout.fields/cover
