title: Product

options:
  changeTemplate: false
  move: false
  delete: false

columns:
  left:
    width: 2/3
    fields:
      price: stripe.checkout.fields/price
  right:
    width: 1/3
    fields:
      image: stripe.checkout.fields/image
