title: programmatordev.stripe-checkout.area.label
icon: settings

options:
  changeSlug: false
  changeStatus: false
  changeTemplate: false
  changeTitle: false
  delete: false
  duplicate: false
  move: false
  preview: false

sections:
  settings:
    type: fields
    fields:
      priceSource:
        label: programmatordev.stripe-checkout.settings.priceSource.label
        help: programmatordev.stripe-checkout.settings.priceSource.help
        type: select
        required: false
        translate: false
        options:
          kirby: programmatordev.stripe-checkout.settings.priceSource.kirby
          stripe: programmatordev.stripe-checkout.settings.priceSource.stripe
