<?php

declare(strict_types=1);

namespace ProgrammatorDev\StripeCheckout\Order\Internal;

use DateTimeImmutable;
use Kirby\Data\Yaml;
use ProgrammatorDev\StripeCheckout\Checkout\CheckoutSource;
use ProgrammatorDev\StripeCheckout\Lifecycle\Internal\HookDeliveryLedger;
use ProgrammatorDev\StripeCheckout\Money\StripeCurrencyRegistry;
use ProgrammatorDev\StripeCheckout\Order\CheckoutStatus;
use ProgrammatorDev\StripeCheckout\Order\DisputeStatus;
use ProgrammatorDev\StripeCheckout\Order\Exception\OrderDataException;
use ProgrammatorDev\StripeCheckout\Order\OrderCreationContext;
use ProgrammatorDev\StripeCheckout\Order\PaymentStatus;
use ProgrammatorDev\StripeCheckout\Order\RefundStatus;
use Throwable;

/**
 * @internal Encodes the canonical projection, not Pages or custom fields.
 * Provider snapshots acquire their own strict schemas with their owning features;
 * reserved names alone never permit arbitrary provider data into order content.
 */
final class OrderSerializer
{
    /**
     * Prepares content for creation, retaining the context's pre-generated UUID.
     * No Page is created or UUID generated by this operation.
     *
     * @return array<string, mixed>
     */
    public static function creation(
        OrderCreationContext $context,
        string $tokenHash,
        string $requestFingerprint,
        ?string $guestReference,
        DateTimeImmutable $createdAt,
    ): array {
        return self::normalize([
            'title' => $context->orderNumber(),
            'uuid' => $context->uuid(),
            'stripeCheckout' => [
                'owner' => OrderSchema::OWNER,
                'schemaVersion' => OrderSchema::VERSION,
            ],
            'orderNumber' => $context->orderNumber(),
            'checkoutAttempt' => [
                'tokenHash' => $tokenHash,
                'requestFingerprint' => $requestFingerprint,
                'source' => $context->sourceType()->value,
                'cartRevision' => $context->cartRevision(),
                'guestReference' => $guestReference,
                'uiMode' => $context->uiMode(),
            ],
            'userUuid' => $context->userUuid(),
            'languageCode' => $context->languageCode(),
            'checkoutStatus' => CheckoutStatus::Creating->value,
            'paymentStatus' => PaymentStatus::Unpaid->value,
            'refundStatus' => RefundStatus::None->value,
            'disputeStatus' => DisputeStatus::None->value,
            ...array_fill_keys(OrderSchema::FLAGS, false),
            'currency' => $context->currency(),
            'subtotal' => (string) $context->subtotal()->getAmount(),
            'refundedTotal' => '0',
            'createdAt' => OrderData::timestamp($createdAt),
            'updatedAt' => OrderData::timestamp($createdAt),
            'initiatingLineItems' => $context->lineItems(),
        ]);
    }

    /**
     * @param array<string, mixed> $data
     * @return array<string, string>
     */
    public static function encode(array $data): array
    {
        $fields = [];

        foreach (self::normalize($data) as $field => $value) {
            $fields[$field] = match (true) {
                is_array($value) => Yaml::encode($value),
                is_bool($value) => $value ? 'true' : 'false',
                is_string($value) => $value,
                default => throw new OrderDataException(),
            };
        }

        return $fields;
    }

    /**
     * @param array<string, mixed> $fields
     * @return array<string, mixed>
     */
    public static function decode(array $fields, string $template, string $slug): array
    {
        if ($template !== OrderSchema::TEMPLATE) {
            throw new OrderDataException();
        }

        try {
            $names = array_combine(array_map(strtolower(...), OrderSchema::fields()), OrderSchema::fields());
            $data = [];

            foreach ($fields as $field => $value) {
                $name = $names[strtolower($field)] ?? null;

                // The caller may pass complete native content; custom fields are
                // outside this projection and must survive the eventual Page merge.
                if ($name === null) {
                    continue;
                }

                if (array_key_exists($name, $data) || is_string($value) === false) {
                    throw new OrderDataException();
                }

                $data[$name] = match (true) {
                    in_array($name, OrderSchema::SNAPSHOTS, true) => Yaml::decode($value),
                    in_array($name, OrderSchema::FLAGS, true) => match ($value) {
                        'true' => true,
                        'false' => false,
                        default => throw new OrderDataException(),
                    },
                    default => $value,
                };
            }

            $data = self::normalize($data);

            if ($data['uuid'] !== $slug) {
                throw new OrderDataException();
            }

            return $data;
        } catch (Throwable) {
            throw new OrderDataException();
        }
    }

    /** @param array<string, mixed> $data */
    public static function hash(array $data): string
    {
        // This is a comparison value, not new persisted revision/hash metadata.
        return hash('sha256', OrderData::json(self::normalize($data)));
    }

    /**
     * @param array<string, mixed> $data
     * @return array<string, mixed>
     */
    public static function normalize(array $data): array
    {
        try {
            OrderData::validateAllowedKeys($data, OrderSchema::fields());
            // Only top-level null means an absent field. Keep explicit zero/false
            // and nested nulls, which carry different snapshot meanings.
            $data = array_filter($data, static fn(mixed $value): bool => $value !== null);
            $required = ['title', 'uuid', 'stripeCheckout', 'orderNumber', 'checkoutAttempt', 'checkoutStatus', 'paymentStatus', 'refundStatus', 'disputeStatus', 'currency', 'subtotal', 'refundedTotal', 'createdAt', 'updatedAt', 'initiatingLineItems', ...OrderSchema::FLAGS];

            OrderData::validateRequiredKeys($data, $required);

            $data = OrderData::map($data);

            $expectedMetadata = [
                'owner' => OrderSchema::OWNER,
                'schemaVersion' => OrderSchema::VERSION,
            ];

            if ($data['stripeCheckout'] !== $expectedMetadata) {
                throw new OrderDataException();
            }

            $uuid = OrderData::text($data['uuid']);
            $orderNumber = OrderData::text($data['orderNumber'], 80);

            if ($data['title'] !== $data['orderNumber']) {
                throw new OrderDataException();
            }

            $checkoutStatus = CheckoutStatus::from(OrderData::text($data['checkoutStatus']));
            $paymentStatus = PaymentStatus::from(OrderData::text($data['paymentStatus']));
            RefundStatus::from(OrderData::text($data['refundStatus']));
            DisputeStatus::from(OrderData::text($data['disputeStatus']));

            foreach (OrderSchema::FLAGS as $field) {
                if (is_bool($data[$field]) === false) {
                    throw new OrderDataException();
                }
            }

            $registry = new StripeCurrencyRegistry();
            $currency = OrderData::text($data['currency']);

            foreach (OrderSchema::AMOUNTS as $field) {
                if (isset($data[$field])) {
                    $money = $registry->toMoney($registry->fromDecimal(OrderData::text($data[$field]), $currency));
                    $data[$field] = $money->isZero() ? '0' : (string) $money->getAmount();
                }
            }

            self::validateTimestamps($data, $checkoutStatus);

            foreach (OrderSchema::REFERENCES as $field => $prefix) {
                if (isset($data[$field])) {
                    $reference = OrderData::text($data[$field], 255);

                    if (preg_match('/\A' . $prefix . '[A-Za-z0-9_]+\z/', $reference) !== 1) {
                        throw new OrderDataException();
                    }
                }
            }

            $attempt = self::validateCheckoutAttempt($data);

            $context = new OrderCreationContext(
                $uuid,
                $orderNumber,
                CheckoutSource::from(OrderData::text($attempt['source'])),
                OrderData::nullableString($attempt['cartRevision']),
                OrderData::nullableString($data['userUuid'] ?? null),
                OrderData::nullableString($data['languageCode'] ?? null),
                OrderData::text($attempt['uiMode']),
                $currency,
                array_map(static fn(mixed $lineItem): OrderLineItemSnapshot => OrderLineItemSnapshot::fromArray(OrderData::map($lineItem)), OrderData::list($data['initiatingLineItems'])),
            );
            $data['initiatingLineItems'] = $context->lineItems();

            $subtotal = $registry->toMoney($registry->fromDecimal(OrderData::text($data['subtotal']), $currency));

            // Before completion, subtotal describes the initiating lines. Completed
            // provider totals are separate facts, not a locally reconstructed tax equation.
            if ($checkoutStatus !== CheckoutStatus::Complete && $subtotal->isEqualTo($context->subtotal()) === false) {
                throw new OrderDataException();
            }

            self::validateState($data, $checkoutStatus, $paymentStatus);

            if (isset($data['lifecycleDeliveries'])) {
                $data['lifecycleDeliveries'] = HookDeliveryLedger::normalize($data['lifecycleDeliveries'], $uuid);
            }

            $deferredSnapshots = array_diff(OrderSchema::SNAPSHOTS, ['stripeCheckout', 'checkoutAttempt', 'initiatingLineItems', 'lifecycleDeliveries']);

            foreach ($deferredSnapshots as $field) {
                if (isset($data[$field]) && $data[$field] !== []) {
                    throw new OrderDataException();
                }
            }

            return $data;
        } catch (Throwable) {
            throw new OrderDataException();
        }
    }

    /**
     * @param array<string, mixed> $data
     * @return array<string, mixed>
     */
    private static function validateCheckoutAttempt(array $data): array
    {
        $attempt = OrderData::map($data['checkoutAttempt']);

        $requiredKeys = ['tokenHash', 'requestFingerprint', 'source', 'cartRevision', 'guestReference', 'uiMode'];
        OrderData::validateAllowedKeys($attempt, $requiredKeys);
        OrderData::validateRequiredKeys($attempt, $requiredKeys);

        $digestFields = ['tokenHash', 'requestFingerprint'];

        foreach ($digestFields as $key) {
            if (is_string($attempt[$key]) === false || preg_match('/\A[a-f0-9]{64}\z/', $attempt[$key]) !== 1) {
                throw new OrderDataException();
            }
        }

        $hasGuest = $attempt['guestReference'] !== null;
        $hasUser = isset($data['userUuid']);

        // Bind the attempt to exactly one actor: a user or an anonymous browser.
        if ($hasGuest === $hasUser) {
            throw new OrderDataException();
        }

        if ($attempt['guestReference'] !== null) {
            OrderData::text($attempt['guestReference']);
        }

        return $attempt;
    }

    /** @param array<string, mixed> $data */
    private static function validateTimestamps(array $data, CheckoutStatus $checkoutStatus): void
    {
        foreach (OrderSchema::TIMESTAMPS as $field) {
            if (isset($data[$field])) {
                OrderData::date($data[$field]);

                // Expiration is a future deadline; the other fields record facts
                // already known at the time this projection was last updated.
                if (
                    $data[$field] < $data['createdAt']
                    || $field !== 'checkoutExpiresAt' && $data[$field] > $data['updatedAt']
                ) {
                    throw new OrderDataException();
                }
            }
        }

        $timestamp = match ($checkoutStatus) {
            CheckoutStatus::Creating => 'createdAt',
            CheckoutStatus::CreationUncertain => 'creationUncertainAt',
            CheckoutStatus::CreationFailed => 'creationFailedAt',
            CheckoutStatus::Open => 'checkoutOpenedAt',
            CheckoutStatus::Complete => 'checkoutCompletedAt',
            CheckoutStatus::Expired => 'checkoutExpiredAt',
        };

        if (isset($data[$timestamp]) === false) {
            throw new OrderDataException();
        }

        // Keep legitimate earlier observations (e.g. uncertainty before opening),
        // but reject mutually exclusive terminal facts. Missing intermediate
        // timestamps are allowed when reconciliation skips an unobserved state.
        $applicableStates = [
            'creationUncertainAt' => [CheckoutStatus::CreationUncertain, CheckoutStatus::CreationFailed, CheckoutStatus::Open, CheckoutStatus::Complete, CheckoutStatus::Expired],
            'creationFailedAt' => [CheckoutStatus::CreationFailed],
            'checkoutOpenedAt' => [CheckoutStatus::Open, CheckoutStatus::Complete, CheckoutStatus::Expired],
            'checkoutCompletedAt' => [CheckoutStatus::Complete],
            'checkoutExpiredAt' => [CheckoutStatus::Expired],
        ];

        foreach ($applicableStates as $field => $states) {
            if (isset($data[$field]) && in_array($checkoutStatus, $states, true) === false) {
                throw new OrderDataException();
            }
        }
    }

    /** @param array<string, mixed> $data */
    private static function validateState(array $data, CheckoutStatus $checkoutStatus, PaymentStatus $paymentStatus): void
    {
        $hasSession = in_array($checkoutStatus, [CheckoutStatus::Open, CheckoutStatus::Complete, CheckoutStatus::Expired], true);

        if ($hasSession !== isset($data['stripeCheckoutSessionId'])) {
            throw new OrderDataException();
        }

        if ($checkoutStatus !== CheckoutStatus::Complete && $paymentStatus !== PaymentStatus::Unpaid) {
            throw new OrderDataException();
        }

        if ($checkoutStatus !== CheckoutStatus::Complete && array_intersect(OrderSchema::FINAL_AMOUNTS, array_keys($data)) !== []) {
            throw new OrderDataException();
        }

        if ($checkoutStatus === CheckoutStatus::Complete) {
            if ($paymentStatus === PaymentStatus::Unpaid) {
                throw new OrderDataException();
            }

            OrderData::validateRequiredKeys($data, OrderSchema::FINAL_AMOUNTS);
        }

        $successfulPayment = in_array($paymentStatus, [PaymentStatus::Paid, PaymentStatus::NoPaymentRequired], true);

        if ($successfulPayment !== isset($data['paidAt'])) {
            throw new OrderDataException();
        }

        // A later authoritative paid observation may correct a failure; retaining
        // that earlier failure timestamp does not make the paid state inconsistent.
        if (isset($data['paymentFailedAt']) && in_array($paymentStatus, [PaymentStatus::Failed, PaymentStatus::Paid], true) === false) {
            throw new OrderDataException();
        }

        if (
            $paymentStatus === PaymentStatus::Failed && isset($data['paymentFailedAt']) === false
            || $paymentStatus === PaymentStatus::NoPaymentRequired && $data['total'] !== '0'
        ) {
            throw new OrderDataException();
        }

        // Non-empty refund/dispute collections are accepted only with their reducers,
        // not by trusting a caller's independently supplied financial summary.
        if (
            $data['refundStatus'] !== RefundStatus::None->value
            || $data['disputeStatus'] !== DisputeStatus::None->value
            || $data['refundedTotal'] !== '0'
            || in_array(true, array_intersect_key($data, array_flip(OrderSchema::FLAGS)), true)
        ) {
            throw new OrderDataException();
        }
    }
}
