title: Product fixture

options:
  changeTemplate: false
  move: false

columns:
  main:
    width: 1/1
    fields:
      price:
        extends: fields/stripe-checkout/price
      stripePrice:
        extends: fields/stripe-checkout/stripe-price
      description:
        extends: fields/stripe-checkout/description
      productImages:
        extends: fields/stripe-checkout/images
      sku:
        extends: fields/stripe-checkout/sku
      requiresShipping:
        extends: fields/stripe-checkout/requires-shipping
      options:
        extends: fields/stripe-checkout/options
      developmentFixture:
        type: hidden
        default: true
