title: Product fixture

options:
  changeTemplate: false
  move: false

columns:
  main:
    width: 1/1
    fields:
      summary:
        type: textarea
        required: true
      stripeCheckoutPrice:
        extends: fields/stripe-checkout/price
      stripeCheckoutDescription:
        extends: fields/stripe-checkout/description
      stripeCheckoutImages:
        extends: fields/stripe-checkout/images
      stripeCheckoutSku:
        extends: fields/stripe-checkout/sku
      stripeCheckoutRequiresShipping:
        extends: fields/stripe-checkout/requires-shipping
      stripeCheckoutOptions:
        extends: fields/stripe-checkout/options
      developmentFixture:
        type: hidden
        default: true
